/* papyrus SQL afpa*/
DROP DATABASE if EXISTS papyrusBDD; /* delete database*/
CREATE DATABASE papyrusBDD;
USE papyrusBDD;

CREATE TABLE `produit` (
  CODART CHAR(4) NOT NULL,
  LIBART VARCHAR(30) NOT NULL,
  STKALE INT NOT NULL,
  STKPHY INT NOT NULL,
  QTEANN INT NOT NULL,
  UNIMES CHAR(5) NOT NULL,
  PRIMARY KEY (CODART)
);

CREATE TABLE `fournis` (
  NUMFOU SMALLINT NOT NULL,
  NOMFOU VARCHAR(25) NOT NULL,
  RUEFOU VARCHAR(50) NOT NULL,
  POSFOU CHAR(5) NOT NULL,
  VILFOU VARCHAR(30) NOT NULL,
  CONFOU VARCHAR(15) NOT NULL,
  SATISF TINYINT(10),
  PRIMARY KEY (NUMFOU)
);

CREATE TABLE `entcom` (
  NUMCOM INT AUTO_INCREMENT,
  OBSCOM VARCHAR(50),
  DATCOM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NUMFOU SMALLINT,
  PRIMARY KEY (NUMCOM),
  FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU)
);

CREATE TABLE `ligcom` (
  NUMLIG TINYINT NOT NULL,
  QTECDE INT NOT NULL,
  PRIUNI DECIMAL(9,2) NOT NULL,
  QTELIV INT,
  DERLIV DATE NOT NULL,
  NUMCOM INT NOT NULL,
  CODART CHAR(4) NOT NULL,
  PRIMARY KEY (NUMCOM,NUMLIG),
  FOREIGN KEY (NUMCOM) REFERENCES entcom(NUMCOM),
  FOREIGN KEY (CODART) REFERENCES produit(CODART)
);

CREATE TABLE `vente` (
  DELLIV SMALLINT NOT NULL,
  QTE1 INT NOT NULL,
  QTE2 INT,
  QTE3 INT,
  PRIX1 DECIMAL(9,2) NOT NULL,
  PRIX2 DECIMAL(9,2),
  PRIX3 DECIMAL(9,2),
  NUMFOU SMALLINT NOT NULL,
  CODART CHAR(4) NOT NULL,
  FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU),
  FOREIGN KEY (CODART) REFERENCES produit(CODART)
);